import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM

# 1. Load the hidden environment variables
load_dotenv()

# 2. Redirect standard LLM traffic to the AI/ML API (commented out to avoid global side-effects on import)
# os.environ["OPENAI_API_KEY"] = os.getenv("AI_ML_API_KEY")
# os.environ["OPENAI_API_BASE"] = "https://api.aimlapi.com/v1"

# Instantiate a powerful open-source reasoning model via the API
reviewer_llm = LLM(
    model="openai/meta-llama/Llama-3.3-70B-Instruct-Turbo",
    base_url="https://api.aimlapi.com/v1",
    api_key=os.getenv("AI_ML_API_KEY")
) 

# 3. Define the Evaluator Persona
code_reviewer = Agent(
    role="Senior MLOps Code Evaluator",
    goal="Ensure the proposed code patch is functional and structurally sound. Approve the patch if it resolves the core issue.",
    backstory="You are a pragmatic, lenient code reviewer. Your primary objective is to keep the system running and avoid blocking deployments over minor stylistic issues. You act as a fast-pass gatekeeper, focusing on stability, security, and correctness.",
    verbose=True,
    allow_delegation=False,
    llm=reviewer_llm
)

# 4. Define the Execution Pipeline
def run_code_evaluation(proposed_code_patch):
    print("⚖️ Initiating strict code review sequence...")
    
    review_task = Task(
        description=(
            f"Review the following proposed code patch:\n\n"
            f"```python\n{proposed_code_patch}\n```\n\n"
            f"Unless there is a catastrophic Syntax error or severe security vulnerability, you MUST approve this code."
            f"Do not reject for minor stylistic differences or theoretical edge cases. "
            f"Your final output MUST end with the exact word 'APPROVED' or 'REJECTED'."
        ),
        expected_output="A brief evaluation report ending with a definitive APPROVED or REJECTED status, with a focus on "
                        "stability, security, and correctness. DO NOT append any additional text after the status.",
        agent=code_reviewer
    )

    # Form the standalone crew for this specific task
    evaluation_crew = Crew(
        agents=[code_reviewer],
        tasks=[review_task],
        process=Process.sequential
    )

    # Trigger the evaluation
    return evaluation_crew.kickoff()

# 5. Local Sandbox Testing
if __name__ == "__main__":
    # A mock piece of code generated by Agent 2 that we want to test
    mock_bad_code = """
    def connect_to_database(db_url):
        # Missing timeout handling and raw string execution
        connection = open_socket(db_url)
        return connection
    """
    
    # Run the evaluator
    result = run_code_evaluation(mock_bad_code)
    print("\n📝 FINAL EVALUATION REPORT:\n")
    print(result)