import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM

# 1. Load the hidden environment variables
load_dotenv()

# 2. Redirect standard LLM traffic to the AI/ML API (commented out to avoid global side-effects on import)
# os.environ["OPENAI_API_KEY"] = os.getenv("AI_ML_API_KEY")
# os.environ["OPENAI_API_BASE"] = "https://api.aimlapi.com/v1"

# Instantiate a powerful open-source reasoning model via the API
reviewer_llm = LLM(
    model="openai/meta-llama/Llama-3.3-70B-Instruct-Turbo",
    base_url="https://api.aimlapi.com/v1",
    api_key=os.getenv("AI_ML_API_KEY")
) 

# 3. Define the Evaluator Persona
code_reviewer = Agent(
    role="Senior MLOps Code Evaluator",
    goal="Rigorously evaluate proposed code patches for reasoning accuracy, edge cases, and architectural flaws.",
    backstory="You are a strict technical gatekeeper. Your job is pure model evaluation. You ensure no logic gaps, syntax errors, or hallucinations exist in generated code before deployment.",
    verbose=True,
    allow_delegation=False,
    llm=reviewer_llm
)

# 4. Define the Execution Pipeline
def run_code_evaluation(proposed_code_patch):
    print("⚖️ Initiating strict code review sequence...")
    
    review_task = Task(
        description=(
            f"Critically analyze the following proposed code patch:\n\n"
            f"```python\n{proposed_code_patch}\n```\n\n"
            f"Check for syntax errors, logical gaps, and security flaws. "
            f"If the code is flawless, your final word must be 'APPROVED'. "
            f"If there are errors, detail the flaws and end with 'REJECTED'."
        ),
        expected_output="A structured evaluation report ending with a definitive APPROVED or REJECTED status.",
        agent=code_reviewer
    )

    # Form the standalone crew for this specific task
    evaluation_crew = Crew(
        agents=[code_reviewer],
        tasks=[review_task],
        process=Process.sequential
    )

    # Trigger the evaluation
    return evaluation_crew.kickoff()

# 5. Local Sandbox Testing
if __name__ == "__main__":
    # A mock piece of code generated by Agent 2 that we want to test
    mock_bad_code = """
    def connect_to_database(db_url):
        # Missing timeout handling and raw string execution
        connection = open_socket(db_url)
        return connection
    """
    
    # Run the evaluator
    result = run_code_evaluation(mock_bad_code)
    print("\n📝 FINAL EVALUATION REPORT:\n")
    print(result)