'''test_sentry.py
Pytest suite for the sentry_parser and band_publisher modules.
'''\n\nfrom __future__ import annotations\n\nimport json\nimport os\nfrom pathlib import Path\n\nimport pytest\n\n# Import the modules under test\nfrom agent_1_sentry.sentry_parser import SentryParser, QwenCoderLLM\nfrom agent_1_sentry.band_publisher import BandPublisher\n\n# Mock LLM that returns a predefined JSON string\nclass MockLLM(QwenCoderLLM):\n    def __init__(self, response: str) -> None:\n        self._response = response\n\n    def _call(self, prompt: str, run_manager=None) -> str:  # pragma: no cover\n        # Not used in our tests – invoke uses this method in BaseLLM, but we
        # override ``invoke`` directly for simplicity.
        raise NotImplementedError\n\n    def invoke(self, payload: str) -> str:\n        # The parser calls ``self.llm.invoke(rendered)``; we return the stub.
        return self._response\n\n# Helper to create a minimal valid AgentSpec JSON\nVALID_SPEC_JSON = json.dumps({\n    "data": {\n        "field1": "value1",\n        "field2": 42\n    }\n})\n\ndef test_parser_successful_validation() -> None:\n    parser = SentryParser(llm=MockLLM(VALID_SPEC_JSON))\n    raw_log = "[INFO] Sample log entry for testing"
    spec = parser.parse(raw_log)\n    # The returned object should have the same data structure as the JSON
    assert hasattr(spec, "data")\n    assert spec.data["field1"] == "value1"\n    assert spec.data["field2"] == 42\n\ndef test_parser_invalid_json_raises() -> None:\n    bad_json = "{ not a valid json }"
    parser = SentryParser(llm=MockLLM(bad_json))\n    with pytest.raises(ValueError, match="LLM returned invalid JSON"):\n        parser.parse("irrelevant")\n\ndef test_parser_validation_error_raises() -> None:\n    # Missing required ``data`` field according to the fallback TypedDict
    invalid_json = json.dumps({"unexpected": 123})\n    parser = SentryParser(llm=MockLLM(invalid_json))\n    with pytest.raises(ValueError, match="Validation of parsed data failed"):\n        parser.parse("log")\n\ndef test_band_publisher_success(monkeypatch, tmp_path: Path) -> None:\n    # Mock httpx.Client.post to simulate a successful response\n    class DummyResponse:\n        status_code = 200\n        def raise_for_status(self) -> None:\n            pass\n    def mock_post(self, url, json):  # pragma: no cover\n        return DummyResponse()\n    monkeypatch.setattr('httpx.Client.post', mock_post)\n    publisher = BandPublisher(endpoint="http://example.com/api")\n    spec = {"data": {"key": "value"}}  # simple dict works with fallback TypedDict\n    assert publisher.publish(spec) is True\n\ndef test_band_publisher_timeout(monkeypatch, tmp_path: Path) -> None:\n    # Simulate a timeout exception and verify fallback file creation\n    def mock_post(self, url, json):  # pragma: no cover\n        raise httpx.TimeoutException("timeout")\n    monkeypatch.setattr('httpx.Client.post', mock_post)\n    fallback_file = tmp_path / "band_fallback.json"\n    # Change cwd so fallback writes to tmp_path\n    monkeypatch.chdir(tmp_path)\n    publisher = BandPublisher(endpoint="http://example.com/api", timeout=0.1)\n    spec = {"data": {"key": "value"}}\n    result = publisher.publish(spec)\n    assert result is False\n    # Verify fallback payload exists and contains the expected JSON\n    assert fallback_file.is_file()\n    saved = json.loads(fallback_file.read_text())\n    assert saved == {"data": {"key": "value"}}\n